[tool.pdm]

[project]
name = ""
version = ""
description = ""
authors = [
    {name = "Yuliya Bryukhovskikh", email = "makutu@ereb.ru"},
]
dependencies = [
    "typer>=0.9.0",
    "pydantic>=1.10.8",
]
requires-python = ">=3.11"
license = {text = "MIT"}
